# Generated by Django 4.1.1 on 2022-10-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlocation',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
