# Generated by Django 4.1.1 on 2022-10-09 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_location', '0003_alter_postlocation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 18, 0, 53, 756669), null=True),
        ),
    ]
