# Generated by Django 4.1.1 on 2022-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_location', '0005_remove_postlocation_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
