# Generated by Django 4.1.1 on 2022-10-09 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_location', '0006_alter_postlocation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlocation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 18, 2, 52, 717126), null=True),
        ),
    ]
