# Generated by Django 4.1.1 on 2022-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
