# Generated by Django 4.1.1 on 2022-10-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='familyName',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='givenName',
            field=models.CharField(default='  ', max_length=250),
            preserve_default=False,
        ),
    ]
